### PR TITLE
Use new Travis docker based env and caching

### PR DESCRIPTION
**Pull request by WouterJ**

### CODE REVIEW

**Comment by lsmith77** [comment]
needs a rebase .. but there also seem to be issues with 5.3 and memory use and 2.3 also seems to have issues with request stack .. but this is likely also the case with master.

**Comment by WouterJ** [comment]
@lsmith77 those issues where also in the main branch. Fixed them with https://github.com/symfony-cmf/RoutingAutoBundle/commit/d3f72565579d429847f2d78bc96540882cbb92d6, I'll rebase soon.

**Comment by lsmith77** [comment]
ping

**Comment by WouterJ** [comment]
Rebased

**Pull request merged**
