### PR TITLE
Use latest versions in the test matrix

### PR DESCRIPTION
**Pull request by WouterJ**

### CODE REVIEW

**Comment by lsmith77** [comment]
do we need to remove https://github.com/symfony-cmf/RoutingAutoBundle/blob/master/composer.json#L12?

**Comment by WouterJ** [comment]
nope, it exists in all composer.json files and shouldn't cause any harm (except from our tests relying on unstable versions). We should maybe add `prefer-stable: true` to all our `composer.json` files, what do you think?

Btw, the test failure was fixed by #149

**Comment by lsmith77** [comment]
ok ``prefer-stable: true`` sounds good.

**Comment by lsmith77** [comment]
ping

**Comment by dantleech** [comment]
+1 for this PR. I don't know what the implications of `prefer-stable: true` would be.

I guess that `1.x-dev` would be used if no stable package is available, but does this mean that when developing new features which depend on `dev-master` versions of other bundles the builds will fail?

**Comment by WouterJ** [comment]
> I guess that 1.x-dev would be used if no stable package is available, but does this mean that, when developing new features which depend on dev-master versions of other bundles which have stable versions, the builds will fail?

It'll install the stable version where possible, but fallback to the dev version. E.g. assume the following composer.json file:

```json
{
    "require": {
        "symfony/framework-bundle": "~2.3",
        "symfony-cmf/menu-bundle": "~1.2"
    },
    "minimum_stability": "dev"
}
```

Composer would now install both `symfony/framework-bundle` 2.7-dev and `symfony-cmf/menu-bundle` `1.2-dev`. Now, when adding `"prefer-stable": true`, 2.6.3 and 1.2.0 will be installed.

Assume MenuBundle 1.3 (which will be 2.0 btw) has a nice feature, which you want to implement. You can bump the requirement to `~1.3`. In this case, composer can't find a stable version for that version constraint and will install `1.3-dev`.

**Comment by dantleech** [comment]
ok, that makes sense to me.

**Comment by lsmith77** [comment]
We need to up the memory limit for PHP 5.3 and we need to add handling for the deprecation errors for Symfony 2.3

**Comment by lsmith77** [comment]
https://travis-ci.org/symfony-cmf/RoutingAutoBundle/jobs/63940446#L456

```
Symfony\Cmf\Bundle\RoutingAutoBundle\Tests\WebTest\RedirectTest::testRedirect
PHPCR\RepositoryException: You need to be logged in for this operation
```

**Comment by lsmith77** [comment]
will look into this tonight (along with #157)

**Comment by lsmith77** [comment]
closing in favor of #158

**Pull request closed without merging**
