### PR TITLE
Convert non-managed intermediate nodes into AutoRoute documents

### PR DESCRIPTION
**Pull request by mmenozzi**
This is a backport on 1.0 branch of the feature/bugfix for the
Generic intermediates nodes which now will be converted in
AutoRoute if needed.

### CODE REVIEW

**Comment by dantleech** [comment]
@WouterJ @dbu seems to be failing because of the deprecation notice, do we need to add `SYMFONY_DEPRECATIONS_HELPER=weak` to the travis environment?

**Comment by WouterJ** [comment]
@dantleech no, we can fix the method calls (don't have to be done in this PR though).

**Comment by mmenozzi** [comment]
@dantleech can we go for the 1.0.2 ?

**Comment by dantleech** [comment]
@mmenozzi can you add the `SYMFONY_DEPRECATIONS_HELPER=weak` to the `travis.yml` file in this PR, e.g. https://github.com/symfony-cmf/RoutingAutoBundle/blob/master/.travis.yml#L18

Then the tests should be green and this PR will be mergable.

**Comment by WouterJ** [comment]
@dantleech just fix the calls to use getParentDocument instead of getParent.

**Comment by dantleech** [comment]
@mmenozzi ^^ that :)

**Comment by mmenozzi** [comment]
@dantleech @WouterJ done! :)

**Comment by WouterJ** [comment]
:+1:

**Comment by dantleech** [comment]
Have tagged 1.0.2.

**Pull request merged**
